name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sudo npm install -g git://github.com/iterative/cml.git#cml-pr --save 

          git fetch --prune --unshallow
          
          pip install -r requirements.txt

          # Pull dataset with DVC 
          (dvc pull --run-cache -v) || true
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro --pull

          echo 'DVC push cache'
          dvc push --run-cache -v

          test-cml-pr --new-pr 'dvc.lock' '.gitignore' 

         
          cml-send-comment report.md 
          