name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm install -g git://github.com/iterative/cml.git#cml-pr --save 

          git fetch --prune --unshallow
          
          pip install -r requirements.txt

          # Pull dataset with DVC 
          (dvc pull --run-cache -v) || true
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro --pull

          echo 'DVC push cache'
          dvc push --run-cache -v

          cml-pr --new-pr 'dvc.lock' '.gitignore' './**/*.json'

          echo 'CML Report' > report.md
          ((dvc metrics diff -v --show-md master) || echo 'Failed diff') >> report.md

          ((dvc plots diff -v --target loss.csv --show-vega master > vega.json && \
          vl2png vega.json -s 1.3 | cml-publish --md) || echo 'Failed plots diff') >> report.md

          echo 'Send report'
          cml-send-comment report.md 
          